### test home page
GET http://localhost:3010/scores

### test one POST
POST http://localhost:3010/scores
Content-Type: application/json

{
    "name": "No Won",
    "score": 0
}

### test two POST
POST http://localhost:3010/scores
Content-Type: application/json

{
    "name": "Dravis Lakewood",
    "score": 28
}

### test two POST
POST http://localhost:3010/scores
Content-Type: application/json

{
    "name": "Echo Millidottir",
    "score": 43
}

### Test PUT
PUT http://localhost:3010/scores/5f6bccf2b0e1cd0ce47242f7
Content-Type: application/json

{
    "name": "Cal Mandrakeson",
    "score": 34
}

### Test delete
DELETE http://localhost:3010/scores/5f73d94f9f7bc722cc6b1225


### Test delete by name
DELETE http://localhost:3010/scores/
Content-Type: application/json

{
    "name": "Echo Millidottir",
    "score": 43
}